"use client";

import Link from "next/link";
import { useState } from "react";
import type { ReactNode } from "react";

import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { StatCard } from "@/components/ui/stat-card";
import { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { LANDLORD_ROUTES } from "@/constants/landlord";
import { FileTextIcon } from "@/components/icons/file-text-icon";
import { ShieldIcon } from "@/components/icons/shield-icon";
import { WrenchIcon } from "@/components/icons/wrench-icon";
import { CreditCardIcon } from "@/components/icons/credit-card-icon";
import { LockIcon } from "@/components/icons/lock-icon";

const panel = "rounded-lg border border-neutral-200 bg-white p-4 md:p-5";
const title = "font-display text-heading-sm font-semibold text-neutral-900";
const muted = "text-body-sm text-neutral-700";

export function PayoutAccountScreen() {
  return <Screen title="Payout account" description="Where your rent goes once a payment clears and you withdraw it.">
    <section className={panel}><h2 className={title}>Connected account</h2><div className="mt-5 flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-md bg-brand-700 font-semibold text-white">CH</span><div><p className="text-body-md font-semibold text-neutral-900">Chase Checking ····4821</p><p className={muted}>Connected Aug 2, 2023</p></div><span className="ml-auto rounded-full bg-success-50 px-2 py-1 text-label-sm text-success-600">Verified</span></div></section>
    <section className={panel}><h2 className={title}>How your rent moves</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{[["1","Tenant pays","Held securely by Vemra"],["2","Rent due date passes","Funds clear to balance"],["3","You withdraw","Arrives in 1–2 days"]].map(([step,heading,detail]) => <div key={step} className="relative text-center"><span className="mx-auto flex size-6 items-center justify-center rounded-full bg-brand-700 text-label-sm font-semibold text-white">{step}</span><p className="mt-2 text-label-md font-semibold text-neutral-900">{heading}</p><p className={muted}>{detail}</p></div>)}</div></section>
    <section className={panel}><h2 className={title}>Payout schedule</h2><dl className="mt-4 divide-y divide-neutral-100">{[["Withdrawal method","Manual on request"],["Typical arrival time","1–2 business days"],["Platform fee","2.5% per rent payment"],["Held funds right now","₦6,275 available"]].map(([label,value]) => <div key={label} className="flex justify-between gap-4 py-3 text-body-sm"><dt className={muted}>{label}</dt><dd className="font-semibold text-neutral-900">{value}</dd></div>)}</dl></section>
    <Button variant="secondary" className="self-start">Update payout account</Button>
  </Screen>;
}

const statementRows = [["Rent paid Unit 2A","Kwame Boateng","Sep 3 (due)","Held until due","₦1,450"],["Rent cleared Unit 4B","Aisha Bello","Aug 29","Cleared","+₦1,450"],["Withdrawal to Chase 4821","","Aug 28","Withdrawn","-₦2,650"],["Rent cleared 12 Birchwood","Grace Adeyemi","Aug 9","Cleared","+₦1,325"],["Rent cleared Unit 4B","Aisha Bello (installment 1)","Aug 5","Cleared","+₦500"]];

export function StatementScreen({ empty = false }: { empty?: boolean }) {
  return <Screen title="Transaction statement" description="Every rent payment, from when a tenant pays to when it lands in your bank." action={<Button variant="secondary" size="sm">Export CSV</Button>}>
    <div className="grid gap-4 md:grid-cols-3"><StatCard variant="outlined" title="Held (not yet due)" value={empty ? "₦0" : "₦1,450"} subtitle={empty ? "No active pending clearing" : "Unit 2A clears Sep 3"} /><StatCard variant="outlined" title="Cleared, ready to withdraw" value={empty ? "₦0" : "₦6,275"} subtitle={empty ? "0 cleared payments" : "4 payments"} className={!empty ? "text-brand-700" : undefined} /><StatCard variant="outlined" title="Withdrawn this month" value={empty ? "₦0" : "₦4,200"} subtitle={empty ? "0 withdrawals processed" : "2 withdrawals to Chase 4821"} /></div>
    <section className={panel}><h2 className={title}>History</h2>{empty ? <EmptyState className="mt-4 border-0 p-10" icon={<FileTextIcon />} title="No transactions yet" description="Rent payments and withdrawals will appear here once your first tenant pays rent." /> : <Table caption="Transaction history"><TableHead><TableHeaderCell>Transaction</TableHeaderCell><TableHeaderCell>Date</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell><TableHeaderCell align="right">Amount</TableHeaderCell></TableHead><TableBody>{statementRows.map(([transaction,person,date,status,amount]) => <TableRow key={transaction+date}><TableCell isPrimary>{transaction}<span className="block text-label-sm font-normal text-neutral-700">{person}</span></TableCell><TableCell header="Date">{date}</TableCell><TableCell header="Status"><span className="rounded-full bg-success-50 px-2 py-1 text-label-sm text-success-600">{status}</span></TableCell><TableCell header="Amount" align="right" className="font-semibold">{amount}</TableCell></TableRow>)}</TableBody></Table>}</section>
  </Screen>;
}

export function MaintenanceScreen({ empty = false }: { empty?: boolean }) {
  if (empty) return <Screen title="Maintenance Reports" description="Oversee maintenance actions, work orders, and requests across your units."><EmptyState icon={<WrenchIcon />} title="No maintenance reports" description="Maintenance issues reported by tenants appear here. The assigned Vemra Property Admin handles and tracks resolution." action={<Link href={LANDLORD_ROUTES.properties} className="inline-flex h-10 items-center rounded-md bg-brand-700 px-5 text-label-md font-semibold text-white">View Properties</Link>} /></Screen>;
  const rows = [["Maple & 9th, Unit 4B","Kitchen pipe burst & leakage","Plumbing","High","Aisha Bello","Sep 2, 2026","Open"],["Birchwood Lane, Unit 1","Broken living room window...","Structural","Medium","Tunde Alabi","Aug 31, 2026","Scheduled"],["Maple & 9th, Unit 2A","AC unit compressor failure","HVAC","High","Kwame Boateng","Aug 29, 2026","Resolved"],["Cedar Heights, Unit 12","Main lock jam/key missing","Security","High","Chinedu Okafor","Aug 28, 2026","Resolved"]];
  return <Screen title="Maintenance Reports" description="Oversee maintenance actions, work orders, and requests across your units." action={<Button size="sm">Log new issue</Button>}><div className="grid gap-4 md:grid-cols-3"><StatCard variant="outlined" title="Open Requests" value="3" subtitle="2 require urgent diagnostic" /><StatCard variant="outlined" title="Scheduled Work" value="1" subtitle="Plumbing contractor booked Sep 4" /><StatCard variant="outlined" title="Resolved This Month" value="4" subtitle="Average resolution: 36 hours" /></div><section className={panel}><div className="mb-4 flex gap-2">{["All","Open","Scheduled","Resolved"].map((tab,i)=><button key={tab} className={`rounded-md px-4 py-2 text-label-sm font-semibold ${i===0?"bg-brand-700 text-white":"bg-neutral-900 text-white"}`}>{tab}</button>)}</div><Table caption="Maintenance reports"><TableHead>{["Property","Issue","Category","Urgency","Tenant","Date logged","Status"].map((head)=><TableHeaderCell key={head}>{head}</TableHeaderCell>)}</TableHead><TableBody>{rows.map(row=><TableRow key={row[0]}>{row.map((cell,i)=><TableCell key={cell} isPrimary={i===0} header={["Property","Issue","Category","Urgency","Tenant","Date logged","Status"][i]}>{cell}</TableCell>)}</TableRow>)}</TableBody></Table></section></Screen>;
}

export function CautionDepositsScreen({ empty = false }: { empty?: boolean }) {
  if (empty) return <Screen title="Caution Deposits" description="Manage tenant escrow deposits, propose damage deductions, or trigger refunds."><EmptyState icon={<ShieldIcon />} title="No caution deposits" description="Once tenants pay caution deposits on your properties, they'll be tracked here in escrow until end of tenancy." /></Screen>;
  return <Screen title="Caution Deposits" description="Manage tenant escrow deposits, propose damage deductions, or trigger refunds." action={<div className="flex gap-2"><Button variant="secondary" size="sm">Propose Deduction</Button><Button size="sm">Initiate Refund</Button></div>}><div className="grid gap-4 md:grid-cols-3"><StatCard variant="outlined" title="Total Escrow Deposits Held" value="₦2,580,000" subtitle="Escrow managed by Vemra Trust Bank" /><StatCard variant="outlined" title="Active Tenancies" value="5" subtitle="Across 6 primary listings" /><StatCard variant="outlined" title="Pending Claims" value="1" subtitle="Unit 2A: Kwame Boateng under review" /></div><section className={panel}><h2 className={title}>Property Admin Recommendation Queue</h2><p className={`mt-2 ${muted}`}>Property Admins can investigate move-out conditions and recommend deductions, but only the landlord can approve, execute, or release escrow funds.</p><div className="mt-5 rounded-lg bg-neutral-100 p-4"><p className="text-body-sm font-semibold text-neutral-900">Recommended deduction</p><p className={muted}>Assigned Property Admin: Funke Adeyemi · Maple & 9th, Unit 2A · Tenant: Kwame Boateng</p><div className="mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-md bg-white p-3"><p className={muted}>Recommended deduction amount</p><p className="text-heading-sm font-bold text-brand-700">₦180,000</p></div><div className="rounded-md bg-white p-3"><p className={muted}>Current escrow balance</p><p className="text-heading-sm font-bold text-neutral-900">₦1,200,000</p></div></div><p className="mt-3 rounded-md bg-white p-3 text-body-sm"><b>Reason:</b> Kitchen wall scuffing and missing living-room light fixture cover recorded during move-out inspection.</p><div className="mt-4 flex gap-2"><Button size="sm">Approve Deduction</Button><Button variant="secondary" size="sm">Reject Recommendation</Button></div></div></section><section className={panel}><h2 className={title}>Active Deposit Ledger</h2><Table caption="Active deposit ledger"><TableHead>{["Property","Tenant","Deposit amount","Date secured","Status"].map(head=><TableHeaderCell key={head}>{head}</TableHeaderCell>)}</TableHead><TableBody>{[["Maple & 9th, Unit 4B","Aisha Bello","₦1,290,000","Jan 12, 2026","Held"],["Birchwood Lane, Unit 1","Tunde Alabi","₦1,800,000","Feb 1, 2026","Held"],["Maple & 9th, Unit 2A","Kwame Boateng","₦1,200,000","Jan 3, 2026","Under Review"],["Cedar Heights, Unit 12","Chinedu Okafor","₦2,400,000","Nov 15, 2025","Refunded"]].map(row=><TableRow key={row[0]}>{row.map((cell,i)=><TableCell key={cell} isPrimary={i===0} header={["Property","Tenant","Deposit amount","Date secured","Status"][i]}>{cell}</TableCell>)}</TableRow>)}</TableBody></Table></section></Screen>;
}

export function SettingsScreen() {
  return <Screen title="Settings"><section className={panel}><h2 className={title}>Profile</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><Input label="Full name" defaultValue="Daniel Osei" /><Input label="Email Address" defaultValue="daniel@example.com" type="email" /><Input label="Phone Number" defaultValue="+234 801 234 5678" /><Input label="Password" defaultValue="••••••••••••" type="password" /></div><Button className="mt-4" size="sm">Save changes</Button></section><section className={panel}><h2 className={title}>Notifications</h2><ToggleList items={["Rent payment confirmations","New messages","New applications"]} /></section><section className="flex items-center justify-between rounded-lg border border-error-600 bg-error-50 p-4"><div><h2 className="text-body-md font-semibold text-error-600">Delete account</h2><p className={muted}>Permanently removes your listings and history</p></div><Button variant="destructive" size="sm">Delete account</Button></section></Screen>;
}

export function NotificationPreferencesScreen() {
  return <Screen title="Notification preferences" description="Choose what you hear from us, and how."><div className="space-y-5">{[["Property Admin communication",["Property Admin communication","Assigned Property Admin updates","Property Admin assignment changes"]],["Operations",["Rent-price approval requests","Maintenance updates","Caution-deposit recommendations"]],["Rent & payouts",["Rent and payout events"]],["Account & product",["Account security","Product updates"]]].map(([heading,items])=><section className={panel} key={heading as string}><p className="text-label-sm font-semibold text-brand-700">{heading}</p><div className="mt-3 divide-y divide-neutral-100">{(items as string[]).map((item,i)=><ToggleList key={item} items={[item]} pushDefault={i!==2}/>)}</div></section>)}</div></Screen>;
}

function ToggleList({ items, pushDefault = true }: { items: string[]; pushDefault?: boolean }) {
  const [values,setValues]=useState(items.map((_,i)=>pushDefault && i!==2));
  return <div>{items.map((item,i)=><div key={item} className="flex items-center justify-between gap-4 border-b border-neutral-100 py-3 last:border-0"><div><p className="text-body-sm font-semibold text-neutral-900">{item}</p><p className={muted}>Email and push notifications for {item.toLowerCase()}</p></div><button type="button" aria-pressed={values[i]} onClick={()=>setValues(v=>v.map((x,j)=>j===i?!x:x))} className={`relative h-5 w-8 rounded-full ${values[i]?"bg-brand-700":"bg-neutral-200"}`}><span className={`absolute top-0.5 size-4 rounded-full bg-white transition-transform ${values[i]?"translate-x-3.5":"translate-x-0.5"}`} /></button></div>)}</div>;
}

const applications = [
  ["Samuel Owusu", "SO", "Move-in Sep 15 · Northline Logistics", "New", "2 days ago"],
  ["Ngozi Umeh", "NU", "Move-in Sep 20 · Freelance designer", "Reviewed", "4 days ago"],
  ["Chidi Eze", "CE", "Move-in Oct 1 · Bank teller", "Declined", "6 days ago"],
] as const;

export function ApplicationsScreen({ empty = false }: { empty?: boolean }) {
  if (empty) {
    return <Screen title="Applications" description="Review applications from tenants who want to rent your vacant properties."><EmptyState icon={<FileTextIcon />} title="No applications yet" description="When tenants apply for your vacant properties, their applications will appear here for review." /></Screen>;
  }

  return <Screen title="Vemra Application Queue" description="Vemra is reviewing 3 applications for this vacant unit."><div className="flex flex-wrap gap-2">{["All (3)", "New (1)", "Reviewed (1)", "Decided (1)"].map((filter, index) => <button key={filter} type="button" className={`rounded-full border px-4 py-2 text-label-sm font-semibold ${index === 0 ? "border-brand-700 bg-brand-700 text-white" : "border-neutral-200 bg-white text-neutral-700"}`}>{filter}</button>)}</div><section className="mt-4 space-y-3">{applications.map(([name, initials, summary, status, date]) => <Link key={name} href={`/landlord/applications/${name.toLowerCase().replaceAll(" ", "-")}`} className="flex items-center gap-3 rounded-lg border border-neutral-200 bg-white p-4 transition hover:border-brand-700"><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-neutral-100 text-label-sm font-semibold text-brand-700">{initials}</span><span className="min-w-0 flex-1"><strong className="block text-body-md text-neutral-900">{name}</strong><span className="block truncate text-label-sm text-neutral-700">{summary}</span></span><span className={`rounded-full px-2 py-1 text-label-sm font-semibold ${status === "New" ? "bg-warning-50 text-warning-600" : status === "Declined" ? "bg-error-50 text-error-600" : "bg-neutral-100 text-neutral-700"}`}>{status}</span><span className="hidden text-label-sm text-neutral-700 sm:block">{date}</span></Link>)}</section></Screen>;
}

export function ApplicationReviewScreen() {
  return <Screen title="Review Vemra application" description="Submitted 2 days ago · move-in requested Sep 15"><div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="space-y-5"><section className={panel}><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-lg bg-neutral-100 font-semibold text-brand-700">GA</span><div><h2 className={title}>Grace Adeyemi</h2><p className={muted}>Applying for Unit 3C, Maple &amp; 9th</p></div></div><div className="mt-5 grid gap-4 border-t border-neutral-200 pt-4 sm:grid-cols-2"><div><p className={muted}>Current employer</p><strong>Lagos Design Co.</strong></div><div><p className={muted}>Requested move-in</p><strong>Sep 15, 2026</strong></div></div><p className="mt-5 text-body-sm italic text-neutral-700">&quot;I&apos;m relocating for work and this would be close to my new office. Happy to provide any additional references.&quot;</p></section><section className={panel}><h2 className={title}>Verification documents</h2><div className="mt-4 space-y-2">{["Government ID · Verified", "Proof of income · Verified", "Background & credit check · Clear"].map((item) => <div key={item} className="rounded-md border border-neutral-200 p-3 text-body-sm">{item}</div>)}</div></section></div><section className={panel}><h2 className={title}>Decision</h2><p className={`mt-4 ${muted}`}>Vemra reviews the applicant&apos;s identity, income, background, and suitability. Property Admins process the decision on behalf of Vemra; landlords do not contact or review tenants directly.</p><div className="mt-5 flex flex-col gap-2"><Button size="sm">Approve for lease preparation</Button><Button variant="secondary" size="sm">Request details via Vemra</Button><Button variant="destructive" size="sm">Decline application</Button></div></section></div></Screen>;
}

export function PropertyAdminInviteScreen() {
  return <Screen title="Invite a Property Admin" description="Assign a Vemra Property Admin to help manage your properties and tenant requests."><section className={`${panel} max-w-160`}><h2 className={title}>Property Admin details</h2><div className="mt-4 space-y-4"><Input label="Full name" placeholder="Enter their full name" /><Input label="Email address" type="email" placeholder="name@example.com" /><Input label="Properties to assign" placeholder="Select properties" /></div><Button className="mt-5">Send invite</Button></section></Screen>;
}

export function PaymentBreakdownScreen() { return <Screen title="Select Payment Method" description="Secure payments are fully managed through Vemra Escrow Vault."><div className="grid gap-6 lg:grid-cols-[1.2fr_.9fr]"><div className="space-y-3">{["Direct Bank Transfer","Debit / Credit Card","Vemra Wallet Secure Pay"].map((item,i)=><button key={item} className={`flex w-full items-center gap-4 rounded-lg border p-4 text-left ${i===0?"border-brand-700":"border-neutral-200"}`}><CreditCardIcon /><span><b className="block text-body-md text-neutral-900">{item}</b><small className={muted}>{i===0?"Most popular for high values · 0% fee":"Instant settlement & clearance"}</small></span></button>)}</div><section className={panel}><h2 className={title}>Payment Breakdown</h2>{[["Annual Rent (₦8 & 9th, Unit 2A)","₦1,290,000"],["Caution Deposit (Refundable)","₦1,290,000"],["Service & Estate Surcharge","₦50,000"],["Vemra Platform Settlement Fee","₦32,250"]].map(([label,value])=><div key={label} className="flex justify-between gap-3 py-2 text-body-sm"><span className={muted}>{label}</span><b>{value}</b></div>)}<hr className="my-3 border-neutral-200" /><div className="flex items-center justify-between"><b>Due Total</b><strong className="text-heading-md text-brand-700">₦2,662,250</strong></div><Button fullWidth className="mt-4">Proceed with Transfer</Button><p className="mt-4 text-center text-label-sm text-brand-700"><LockIcon className="mr-1 inline size-4" />Payments fully secured and protected under trust escrow.</p></section></div></Screen>; }

function Screen({ title: heading, description, action, children }: { title: string; description?: string; action?: ReactNode; children: ReactNode }) { return <div className="flex flex-col gap-5 md:gap-6"><div className="flex items-start justify-between gap-4"><div><h1 className="font-display text-heading-lg font-bold text-neutral-900 md:text-heading-xl">{heading}</h1>{description&&<p className={`mt-1 ${muted}`}>{description}</p>}</div>{action}</div>{children}</div>; }
